---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH  
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH