---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp resources $DEPLOYPATH/resources
    - /bin/cp script.js $DEPLOYPATH  
    - /bin/cp style.css $DEPLOYPATH